name: 'Setup tosutil'
description: 'Setup tosutil for your GitHub Actions'
author: 'Yudu Ban'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'cloud'
  color: 'blue'

# Define your inputs here.
inputs:
  endpoint:
    description:
      'Endpoint of your service, for example: tos-cn-shanghai.volces.com'
  region:
    required: true
    description: 'Region name of your service, for example: cn-shanghai'
  access-key-id:
    required: true
    description: 'Access key ID of your account'
  access-key-secret:
    required: true
    description: 'Secret of the access key'
  token:
    description: 'Token'

runs:
  using: node20
  main: dist/index.js
